

# 数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/car_rental
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  resources:
    static-locations: /**
#    static-locations: classpath:/static/**
  devtools:
    restart:
      enabled: true
      additional-paths: /**
#  jackson:
#    date-format:
#  日志
logging:
  level:
    root: error
    com.mingzi: debug
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
#      table-prefix: _
  mapper-locations: classpath:mapper/*Mapper.xml
server:
  servlet:
    context-path: /car
